- name: Enable required cgroup features.
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    state: present
  register: cgroup_features

- name: Reboot immediately if cgroup features changed.
  reboot:
    pre_reboot_delay: 2
    post_reboot_delay: 2 
    reboot_timeout: 600
    msg: Reboot initiated by Ansible 
  when: cgroup_features is changed

- name: Install k3s master
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /var/lib/rancher/k3s/server/node-token
  when:
  - "'masters' in group_names"

- name: Get the node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  when: "'masters' in group_names"
     
# - name: print token
#   debug:
#     msg:  "{{ hostvars[groups['masters'][0]].k3s_token['content'] | b64decode  | trim }}"  
#   when: "'nodes' in group_names"

- name: Install k3s nodes
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
  environment:
    K3S_URL: "https://{{ hostvars[groups['masters'][0]].ansible_hostname }}:6443"
    K3S_TOKEN: "{{ hostvars[groups['masters'][0]].k3s_token['content'] | b64decode  | trim }}"
  when:
  - "'nodes' in group_names"